import Image from "next/image";
import { allSurah, useparapstype, suraxytpe } from "../../Interface";
import ReactAudioPlayer from "react-audio-player";
import { useLangData } from "../../Zuztand/Langue";
import stayle from "./main.module.scss";
import Head from "next/head";
import { useEffect, useState } from "react";
import { FloatButton } from "antd";

export const getStaticPaths = async () => {
  const res = await fetch(`https://api.alquran.cloud/v1/surah`);
  const repo = await res.json();
  const paths = repo?.data?.map((p: allSurah) => {
    return {
      params: {
        suraxId: `${p?.number}`,
      },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async (context: useparapstype) => {
  const { params } = context;

  const uzb = await fetch(
    `https://quranenc.com/api/v1/translation/sura/uzbek_mansour/${params.suraxId}`
  );
  const Uzbrepo = await uzb.json();

  const rus = await fetch(
    `https://quranenc.com/api/v1/translation/sura/english_rwwad/${params.suraxId}`
  );
  const Rusrepo = await rus.json();

  const tur = await fetch(
    `https://quranenc.com/api/v1/translation/sura/turkish_shaban/${params.suraxId}`
  );
  const Turrepo = await tur.json();

  const audyo = await fetch(
    `http://api.alquran.cloud/v1/surah/${params.suraxId}/ar.alafasy`
  );

  const audyodata = await audyo.json();
  return { props: { Uzbrepo, Rusrepo, Turrepo, audyodata } };
};

const SuraxDetel = ({ Uzbrepo, Rusrepo, Turrepo, audyodata }: any) => {
  const [number, setNumber] = useState<number>(0);
  const [data, setData] = useState<any>();
  const [lang, setLange] = useState<any>({});
  const { langue, setLang } = useLangData();

  useEffect(() => {
    if (langue === "uzb") {
      setLange(Uzbrepo);
    } else if (langue === "tur") {
      setLange(Rusrepo);
    } else if (langue === "eng") {
      setLange(Turrepo);
    }
  }, [lang, langue]);

  return (
    <div>
      <Head>
        <title>{audyodata?.data?.englishName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Images/quran-icon.png" />
      </Head>
      <div className={`${stayle.wrapper}  container text-center`}>
        <h1 className="text-center text-black text-[40px] underline font-mono pt-4">
          {audyodata?.data?.englishName}
        </h1>
        <div>
          {lang?.result?.map((e: suraxytpe) => (
            <div key={e.id} className={`${stayle.wrapper__box}`}>
              <div className={stayle.wrapper__box1}>
                <Image
                  src="/Images/bootom.png"
                  width="200"
                  height="180"
                  alt="Abstrakt image ayat number"
                ></Image>
                <h1 className={stayle.wrapper__number}>{e.aya}</h1>
              </div>
              <h1 className={stayle.wrapper__translate}>{e.translation}</h1>
              <h1 className={stayle.wrapper__text}>{e.arabic_text}</h1>
              <div className={stayle.wrapper__folder}>
                <button
                  onClick={() => (
                    setNumber(Number(e?.aya)), setData(audyodata?.data?.ayahs)
                  )}
                  className="text-[35px] rounded"
                >
                  ▶️
                </button>
              </div>
            </div>
          ))}
        </div>

        {data ? (
          <div className={stayle.box}>
            <h1>{data[number - 1]?.text}</h1>
            <div className="flex items-center">
              <div className="flex gap-4">
                <button
                  onClick={() => setNumber(number === 1 ? number : number - 1)}
                  className="text-[30px]"
                >
                  ⏮️
                </button>
                <button
                  onClick={() => setNumber(number + 1)}
                  className="text-[30px]"
                >
                  ⏩
                </button>
              </div>
              <ReactAudioPlayer
                style={{ backgroundColor: "lightblue" }}
                className={stayle.box__audyo}
                src={audyodata?.data?.ayahs[number - 1]?.audio}
                onEnded={() => setNumber(number + 1)}
                autoPlay
                controls
              />
              <button onClick={() => setData(false)} className="text-[30px]">
                ⏺️
              </button>
            </div>
          </div>
        ) : (
          ""
        )}
      </div>
      <FloatButton.Group
        trigger="click"
        type="primary"
        shape="circle"
        style={{ right: 24 }}
        icon={<i className="fa-solid fa-earth-americas"></i>}
      >
        <FloatButton description="UZB" onClick={() => setLang("uzb")} />
        <FloatButton description="ENG" onClick={() => setLang("tur")} />
        <FloatButton description="TUR" onClick={() => setLang("eng")} />
      </FloatButton.Group>
    </div>
  );
};

export default SuraxDetel;
