import Link from "next/link";
import { instance } from "../../Utils/axios";
import { allSurah } from "../../Interface";
import stayle from "./stayle.module.scss";
import Head from "next/head";

export const getStaticProps = async () => {
  const res = await fetch("https://api.alquran.cloud/v1/surah");
  const datamap = await res.json();
  return { props: { datamap } };
};

interface allsura {
  code: number;
  datamap: allSurah;
  status: string;
  data: [];
}

const Surax = ({ datamap }: allsura) => {
  return (
    <div>
      <Head>
        <title>All Surah</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Images/quran-icon.png" />
      </Head>
      <div className={`${stayle.wrapper} container`}>
        <div className={stayle.wrapper__box}>
          {datamap?.data?.map((e: allSurah) => (
            <Link key={e.number} href={`/surax/${e.number}`}>
              <a>
                <div className={stayle.wrapper__card} key={e.number}>
                  <h1>{e.number}</h1>
                  <h1>{e.englishName}</h1>
                  <h1>{e.name}</h1>
                  <h1>{e.revelationType === "Meccan" ? "🕋" : "🕌"}</h1>
                </div>
              </a>
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Surax;
