import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import stayle from "./stayle.module.scss";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>All Quran App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Images/quran-icon.png" />
      </Head>

      <div className={`${stayle.home} bg-blue-700 h-screen`}>
        <div className={stayle.home__wrapper}>
          <Image
            className={stayle.home__image}
            width="200"
            height="200"
            alt="All-Quran App logo"
            src="/Images/quran-icon.png"
          ></Image>
        </div>
        <Link href={`surax`}>
          <h1>My Quran App</h1>
        </Link>
      </div>
    </div>
  );
};

export default Home;
